### ISSUE TITLE
[1.11.2][Bug] Crash on world load

### ISSUE THREAD

**Issue by MysticAura** [TTFTCUTS/ATG#12]
MC: 1.11.2
Forge: 2310
Mod: atg-1.11.2-2.1.4

Crash on world creation. 

[Crash Log](https://pastebin.com/JB5dUaaX)

**Comment by ghost** [comment]
i'm getting this crash too, i think it happened after updating natura or hammer core
[crash-2017-05-31_17.27.44-server.txt](https://github.com/TTFTCUTS/ATG/files/1041852/crash-2017-05-31_17.27.44-server.txt)

**Comment by TTFTCUTS** [comment]
Duplicate of #6 
Another mod is raising an error during the ice chunk population event, seemingly due to a mob spawning.

Not my fault, it's just passing through the ATG chunk provider. It may be to do with the _conditions_ present because of ATG such as increased height, but the fault is on their side from what I can tell.
